# -*- coding: utf-8 -*-
"""kelime_sayıları.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mF6auqvQnZzahRT3QiDeN86RwjrKaGlj
"""

import pandas as pd
import numpy as np

train=pd.read_excel("clean_tweet_train.xlsx")
test=pd.read_excel("clean_tweet_test.xlsx")

Train = train.append(test, ignore_index=True).fillna(' ')
kelimeler = Train.text.to_string().split()

from collections import Counter
kelime_sayi = Counter(kelimeler)

print(type(kelime_sayi), '\n')

for kelime in kelime_sayi.most_common(5000):
    print(kelime)